version: "3"

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: tweeter
      MYSQL_ROOT_PASSWORD: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
      DATABASE_HOST: db
  web:
    build: ./src
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./src:/opt/app:cached
    working_dir: /opt/app
    ports:
      - "8000:8000"
      - "5858:5858"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tweeter
      MYSQL_USER: node
      MYSQL_PASSWORD: node
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: node
