version: "3"

services:
  db:
    #build: ./db
    image: "mysql:5.7"
    container_name: "node-mysql"
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: tweeter
      MYSQL_ROOT_PASSWORD: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
      DATABASE_HOST: db
  web:
    build: ./src
    container_name: "node-api"
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./src:/opt/app:cached
    working_dir: /opt/app
    ports:
      - "8001:8001"
      - "5859:5859"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tweeter
      MYSQL_USER: node
      MYSQL_PASSWORD: node
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: db
      TYPEORM_USERNAME: node
      TYPEORM_PASSWORD: node
      TYPEORM_DATABASE: tweeter
      TYPEORM_ENTITIES: /opt/app/build/api/entity/*.js
  phpmyadmin:
    container_name: "node-api-phpmyadmin"
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: node
