CREATE TABLE tweet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  body VARCHAR(255) NOT NULL,
  parent INT,
  userId INT
) DEFAULT CHARSET=utf8;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
) DEFAULT CHARSET=utf8;

CREATE TABLE likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  tweetId INT NOT NULL
) DEFAULT CHARSET=utf8;
