CREATE TABLE tweet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  body TEXT NOT NULL,
  parent INT,
  userId INT NOT NULL,
  createdAt DATETIME NOT NULL,
  deleted TINYINT NOT NULL DEFAULT '0'
) DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
) DEFAULT CHARSET=utf8;

CREATE TABLE `like` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  tweetId INT NOT NULL
) DEFAULT CHARSET=utf8;
